### ISSUE TITLE
Doesn't works

### ISSUE THREAD

**Issue by ZhymabekRoman** [Neilpang/wgcf-docker#13]
Thanks for the project!

Docker compose file:
```
version: '3'

services:
  wgcf1:
    image: neilpang/wgcf-docker:latest
    volumes:
      - ./service/wgcf1:/wgcf
      - /lib/modules:/lib/modules
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
    cap_add:
      - NET_ADMIN
    restart: always
    healthcheck:
      test: curl -fs https://www.cloudflare.com/cdn-cgi/trace | grep -q -E 'warp=(on|plus)' && exit 0 || exit 1
      interval: 5s
      timeout: 45s
      retries: 10
```
Log file: 
[output.txt](https://github.com/Neilpang/wgcf-docker/files/13607840/output.txt)

wgcf works great outside of the Docker container
